### ISSUE TITLE
Doesnt Work

### ISSUE THREAD

**Issue by bakes82** [benagain/FunctionAppWithAsbAndMI#1]
Do you have a version that works with the current state of azure/nservicebus?

**Comment by benagain** [comment]
Hi @bakes82, I haven't used the latest NServiceBus.AzureFunctions.InProcess library I'm afraid.  

It looks like there is [still a constructor that takes the configuration factory](https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/blob/1e97d74654bb0941c417091f098f8bb4268d603b/src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs#L18-L20), have you tried using that?

I would suggest asking in [Particlar's discussion group](https://discuss.particular.net/) - I've found them to be very helpful and responsive.
